-- Add up migration script here

INSERT INTO author (author_name) VALUES ('Steve Jobs');
INSERT INTO author (author_name) VALUES ('Ralph Waldo Emerson');
INSERT INTO author (author_name) VALUES ('Albert Einstein');
INSERT INTO author (author_name) VALUES ('Franklin D. Roosevelt');
INSERT INTO author (author_name) VALUES ('Robert Frost');
INSERT INTO author (author_name) VALUES ('Nelson Mandela');
INSERT INTO author (author_name) VALUES ('Winston Churchill');
INSERT INTO author (author_name) VALUES ('John Lennon');
INSERT INTO author (author_name) VALUES ('Stephen R. Covey');
INSERT INTO author (author_name) VALUES ('Martin Luther King Jr.');
INSERT INTO author (author_name) VALUES ('Brian Tracy');
INSERT INTO author (author_name) VALUES ('Jordan Belfort');
INSERT INTO author (author_name) VALUES ('J.K. Rowling');
INSERT INTO author (author_name) VALUES ('Dalai Lama');
INSERT INTO author (author_name) VALUES ('Wayne Gretzky');
INSERT INTO author (author_name) VALUES ('Walt Disney');
INSERT INTO author (author_name) VALUES ('Dr. Seuss');
INSERT INTO author (author_name) VALUES ('Theodore Roosevelt');
INSERT INTO author (author_name) VALUES ('Confucius');
INSERT INTO author (author_name) VALUES ('Johann Wolfgang von Goethe');
INSERT INTO author (author_name) VALUES ('William Butler Yeats');
INSERT INTO author (author_name) VALUES ('William Shakespeare');
INSERT INTO author (author_name) VALUES ('Peter Drucker');
INSERT INTO author (author_name) VALUES ('Vidal Sassoon');
INSERT INTO author (author_name) VALUES ('Thomas Jefferson');
INSERT INTO author (author_name) VALUES ('Charles R. Swindoll');
INSERT INTO author (author_name) VALUES ('C.S. Lewis');
INSERT INTO author (author_name) VALUES ('Eleanor Roosevelt');
INSERT INTO author (author_name) VALUES ('Chris Grosser');
INSERT INTO author (author_name) VALUES ('Sam Levenson');
INSERT INTO author (author_name) VALUES ('Anonymous');
INSERT INTO author (author_name) VALUES ('Vincent van Gogh');
INSERT INTO author (author_name) VALUES ('Henry David Thoreau');
COMMIT;
INSERT INTO quote (text, author_id) VALUES ($$The only way to do great work is to love what you do.$$, 1);
INSERT INTO quote (text, author_id) VALUES ($$To be yourself in a world that is constantly trying to make you something else is the greatest accomplishment.$$, 2);
INSERT INTO quote (text, author_id) VALUES ($$Two things are infinite: the universe and human stupidity; and I'm not sure about the universe.$$, 3);
INSERT INTO quote (text, author_id) VALUES ($$The only limit to our realization of tomorrow will be our doubts of today.$$, 4);
INSERT INTO quote (text, author_id) VALUES ($$In three words I can sum up everything I've learned about life: it goes on.$$, 5);
INSERT INTO quote (text, author_id) VALUES ($$The only thing we have to fear is fear itself.$$, 4);
INSERT INTO quote (text, author_id) VALUES ($$The greatest glory in living lies not in never falling, but in rising every time we fall.$$, 6);
INSERT INTO quote (text, author_id) VALUES ($$Success is not final, failure is not fatal: It is the courage to continue that counts.$$, 7);
INSERT INTO quote (text, author_id) VALUES ($$Life is what happens when you're busy making other plans.$$, 8);
INSERT INTO quote (text, author_id) VALUES ($$I am not a product of my circumstances. I am a product of my decisions.$$, 9);
INSERT INTO quote (text, author_id) VALUES ($$In the end, we will remember not the words of our enemies, but the silence of our friends.$$, 10);
INSERT INTO quote (text, author_id) VALUES ($$You have within you right now, everything you need to deal with whatever the world can throw at you.$$, 11);
INSERT INTO quote (text, author_id) VALUES ($$The only thing standing between you and your goal is the story you keep telling yourself as to why you can't achieve it.$$, 12);
INSERT INTO quote (text, author_id) VALUES ($$It is our choices that show what we truly are, far more than our abilities.$$, 13);
INSERT INTO quote (text, author_id) VALUES ($$The purpose of our lives is to be happy.$$, 14);
INSERT INTO quote (text, author_id) VALUES ($$You miss 100% of the shots you don't take.$$, 15);
INSERT INTO quote (text, author_id) VALUES ($$The way to get started is to quit talking and begin doing.$$, 16);
INSERT INTO quote (text, author_id) VALUES ($$Don't cry because it's over, smile because it happened.$$, 17);
INSERT INTO quote (text, author_id) VALUES ($$Believe you can and you're halfway there.$$, 18);
INSERT INTO quote (text, author_id) VALUES ($$Life is really simple, but we insist on making it complicated.$$, 19);
INSERT INTO quote (text, author_id) VALUES ($$Whatever you can do, or dream you can, begin it. Boldness has genius, power, and magic in it.$$, 20);
INSERT INTO quote (text, author_id) VALUES ($$Do not wait to strike till the iron is hot, but make it hot by striking.$$, 21);
INSERT INTO quote (text, author_id) VALUES ($$It is not in the stars to hold our destiny but in ourselves.$$, 22);
INSERT INTO quote (text, author_id) VALUES ($$The best way to predict the future is to create it.$$, 23);
INSERT INTO quote (text, author_id) VALUES ($$Success is stumbling from failure to failure with no loss of enthusiasm.$$, 7);
INSERT INTO quote (text, author_id) VALUES ($$What lies behind us and what lies before us are tiny matters compared to what lies within us.$$, 2);
INSERT INTO quote (text, author_id) VALUES ($$The only place where success comes before work is in the dictionary.$$, 24);
INSERT INTO quote (text, author_id) VALUES ($$I find that the harder I work, the more luck I seem to have.$$, 25);
INSERT INTO quote (text, author_id) VALUES ($$It always seems impossible until it's done.$$, 6);
INSERT INTO quote (text, author_id) VALUES ($$Life is 10% what happens to us and 90% how we react to it.$$, 26);
INSERT INTO quote (text, author_id) VALUES ($$You are never too old to set another goal or to dream a new dream.$$, 27);
INSERT INTO quote (text, author_id) VALUES ($$The future belongs to those who believe in the beauty of their dreams.$$, 28);
INSERT INTO quote (text, author_id) VALUES ($$You have brains in your head. You have feet in your shoes. You can steer yourself any direction you choose.$$, 17);
INSERT INTO quote (text, author_id) VALUES ($$The only person you are destined to become is the person you decide to be.$$, 2);
INSERT INTO quote (text, author_id) VALUES ($$Opportunities don't happen. You create them.$$, 29);
INSERT INTO quote (text, author_id) VALUES ($$Happiness is not something ready made. It comes from your own actions.$$, 14);
INSERT INTO quote (text, author_id) VALUES ($$Don't watch the clock; do what it does. Keep going.$$, 30);
INSERT INTO quote (text, author_id) VALUES ($$If you want to achieve greatness stop asking for permission.$$, 31);
INSERT INTO quote (text, author_id) VALUES ($$I would rather die of passion than of boredom.$$, 32);
INSERT INTO quote (text, author_id) VALUES ($$Success usually comes to those who are too busy to be looking for it.$$, 33);
COMMIT;
